const dictionary = {
"Урок 1": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "der Cousin", ru: "Двоюродный брат" },
  { type: "noun", de: "die Cousine", ru: "Двоюродная сестра" },
  { type: "noun", de: "der Neffe", ru: "Племянник" },
  { type: "noun", de: "die Nichte", ru: "Племянница" },
  { type: "noun", de: "der Onkel", ru: "Дядя" },
  { type: "noun", de: "die Tante", ru: "Тётя" },
  { type: "noun", de: "der Schwiegersohn", ru: "Зять" },
  { type: "noun", de: "die Schwiegertochter", ru: "Невестка" },
  { type: "noun", de: "die Schwiegermutter", ru: "Тёща, свекровь" },
  { type: "noun", de: "der Schwiegervater", ru: "Тесть, свёкор" },
  { type: "noun", de: "die Geschichte", ru: "История" },
  { type: "noun", de: "der Jugendliche", ru: "Подросток" },
  { type: "noun", de: "die Puppe", ru: "Кукла" },
  { type: "noun", de: "die Sache", ru: "Вещь" },
  { type: "noun", de: "das Spiel", ru: "Игра" },
  { type: "noun", de: "der Witz", ru: "Шутка" },
  { type: "noun", de: "der Anfang", ru: "Начало" },
  { type: "noun", de: "das Ende", ru: "Конец" },
  { type: "noun", de: "die Mannschaft", ru: "Команда" },
  { type: "noun", de: "der Pfeffer", ru: "Перец" },
  { type: "noun", de: "der Punkt", ru: "Точка, пункт" },
  { type: "noun", de: "der Satz", ru: "Предложение, фраза" },
  { type: "noun", de: "der Schluss", ru: "Конец, заключение" },
  { type: "noun", de: "das Studium", ru: "Учёба (в вузе)" },
  { type: "noun", de: "die Zigarette", ru: "Сигарета" },

  // ГЛАГОЛЫ
  { type: "verb", de: "klettern", perfekt: "ist geklettert", ru: "заниматься скалолазанием, лезть", context: { de: "Er ist auf den Baum geklettert.", ru: "Он залез на дерево." } },
  { type: "verb", de: "sammeln", perfekt: "hat gesammelt", ru: "собирать, коллекционировать", context: { de: "Die Kinder haben im Wald Pilze gesammelt.", ru: "Дети собрали в лесу грибы." } },
  { type: "verb", de: "streiten", perfekt: "hat gestritten", ru: "спорить, ссориться", context: { de: "Sie haben gestritten und sprechen nicht mehr.", ru: "Они поссорились и больше не разговаривают." } },
  { type: "verb", de: "übernachten", perfekt: "hat übernachtet", ru: "ночевать, оставаться на ночь", context: { de: "Wir haben in einem kleinen Hotel übernachtet.", ru: "Мы переночевали в маленьком отеле." } },
  { type: "verb", de: "verkaufen", perfekt: "hat verkauft", ru: "продавать", context: { de: "Er hat sein Haus verkauft.", ru: "Он продал свой дом." } },
  { type: "verb", de: "zeichnen", perfekt: "hat gezeichnet", ru: "рисовать карандашом/чертить", context: { de: "Der Student hat einen Plan gezeichnet.", ru: "Студент начертил план." } },
  { type: "verb", de: "auf ∙ machen", perfekt: "hat aufgemacht", ru: "открывать", context: { de: "Er hat das Geschenk schnell aufgemacht.", ru: "Он быстро открыл подарок." } },
  { type: "verb", de: "auf ∙ passen", perfekt: "hat aufgepasst", ru: "быть внимательным, следить, присматривать", context: { de: "Sie hat gestern auf die Kinder aufgepasst.", ru: "Вчера она присматривала за детьми." } },
  { type: "verb", de: "klappen", perfekt: "hat geklappt", ru: "получаться, ладиться", context: { de: "Mit dem Termin hat es gut geklappt.", ru: "Всё хорошо получилось со встречей." } },
  { type: "verb", de: "passieren", perfekt: "ist passiert", ru: "происходить, случаться", context: { de: "Was ist hier passiert?", ru: "Что здесь произошло?" } },
  { type: "verb", de: "rufen", perfekt: "hat gerufen", ru: "звать, кричать", context: { de: "Der Arzt hat den Patienten gerufen.", ru: "Врачи позвал пациента." } },
  { type: "verb", de: "wachsen", perfekt: "ist gewachsen", ru: "расти", context: { de: "Die Blume ist schnell gewachsen.", ru: "Цветок быстро вырос." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "verrückt", ru: "сумасшедший, безумный" },
  { type: "other", de: "einfach", ru: "простой / просто" },
  { type: "other", de: "fleißig", ru: "прилежный, старательный" },
  { type: "other", de: "closed", de: "geschlossen", ru: "закрытый" },
  { type: "other", de: "kompliziert", ru: "сложный" },
  { type: "other", de: "früher", ru: "раньше, прежде" },
  { type: "other", de: "am Anfang", ru: "в начале" },
  { type: "other", de: "am Ende", ru: "в конце" },
  { type: "other", de: "zuerst", ru: "сначала, сперва" },
  { type: "other", de: "zum Schluss", ru: "в конце, в заключение" }
],
"Урок 2": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "das Ding", ru: "Вещь, предмет" },
  { type: "noun", de: "die Ecke", ru: "Угол" },
  { type: "noun", de: "das Fernsehgerät", ru: "Телевизор" },
  { type: "noun", de: "der Gegenstand", ru: "Предмет, вещь" },
  { type: "noun", de: "der Herd", ru: "Плита" },
  { type: "noun", de: "das Kissen", ru: "Подушка" },
  { type: "noun", de: "der Raum", ru: "Пространство, комната, помещение" },
  { type: "noun", de: "das Regal", ru: "Полка, стеллаж" },
  { type: "noun", de: "der Schreibtisch", ru: "Письменный стол" },
  { type: "noun", de: "der Spiegel", ru: "Зеркало" },
  { type: "noun", de: "die Tür", ru: "Дверь" },
  { type: "noun", de: "der Vorhang", ru: "Штора, занавеска" },
  { type: "noun", de: "die Wand", ru: "Стена" },
  { type: "noun", de: "das Werkzeug", ru: "Инструмент" },
  { type: "noun", de: "das Heft", ru: "Тетрадь" },
  { type: "noun", de: "das Souvenir", ru: "Сувенир" },

  // ГЛАГОЛЫ
  { type: "verb", de: "ein ∙ richten", perfekt: "hat eingerichtet", ru: "обставлять, устраивать", context: { de: "Wir haben unsere neue Wohnung gemütlich eingerichtet.", ru: "Мы уютно обставили нашу новую квартиру." } },
  { type: "verb", de: "hängen (висеть)", perfekt: "hat gehangen", ru: "Висеть", context: { de: "Das Bild hat an der Wand gehangen.", ru: "Картина висела на стене." } },
  { type: "verb", de: "hängen (вешать)", perfekt: "hat gehängt", ru: "Вешать", context: { de: "Er hat das Bild an die Wand gehängt.", ru: "Он повесил картину на стену." } },
  { type: "verb", de: "legen", perfekt: "hat gelegt", ru: "Класть", context: { de: "Ich habe das Buch auf das Regal gelegt.", ru: "Я положил книгу на полку." } },
  { type: "verb", de: "liegen", perfekt: "hat gelegen", ru: "Лежать", context: { de: "Das Buch hat auf dem Regal gelegen.", ru: "Книга лежала на полке." } },
  { type: "verb", de: "renovieren", perfekt: "hat renoviert", ru: "Ремонтировать, обновлять", context: { de: "Wir haben das Zimmer komplett renoviert.", ru: "Мы полностью отремонтировали комнату." } },
  { type: "verb", de: "stehen", perfekt: "hat gestanden", ru: "Стоять", context: { de: "Der Schreibtisch hat am Fenster gestanden.", ru: "Письменный стол стоял у окна." } },
  { type: "verb", de: "stellen", perfekt: "hat gestellt", ru: "Ставить", context: { de: "Er hat den Stuhl an den Tisch gestellt.", ru: "Он поставил стул к столу." } },
  { type: "verb", de: "diskutieren", perfekt: "hat diskutiert", ru: "Дискутировать, обсуждать", context: { de: "Sie haben lange über das Problem diskutiert.", ru: "Они долго обсуждали эту проблему." } },
  { type: "verb", de: "verstecken", perfekt: "hat versteckt", ru: "Прятать", context: { de: "Die Katze hat sich unter dem Sofa versteckt.", ru: "Кот спрятался под диваном." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "dunkel", ru: "Тёмный" },
  { type: "other", de: "hell", ru: "Светлый" },
  { type: "other", de: "schwer", ru: "Тяжёлый, сложный" },
  { type: "other", de: "vorsichtig", ru: "Осторожный" },
  { type: "other", de: "sonst", ru: "Иначе, в противном случае, еще" },
  { type: "other", de: "in der Ecke", ru: "В углу" },
  { type: "other", de: "vorsichtig sein mit", ru: "Быть осторожным с" }
],
"Урок 3": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "das Dorf", ru: "Деревня, село" },
  { type: "noun", de: "die Katze", ru: "Кошка, кот" },
  { type: "noun", de: "die Pflanze", ru: "Растение" },
  { type: "noun", de: "die Landschaft", ru: "Пейзаж, ландшафт" },
  { type: "noun", de: "die Luft", ru: "Воздух" },
  { type: "noun", de: "die Ruhe", ru: "Покой, тишина, отдых" },
  { type: "noun", de: "der Strand", ru: "Пляж" },
  { type: "noun", de: "das Tier", ru: "Животное" },
  { type: "noun", de: "das Ufer", ru: "Берег (реки, озера, моря)" },
  { type: "noun", de: "der Vogel", ru: "Птица" },
  { type: "noun", de: "die Beratung", ru: "Консультация" },
  { type: "noun", de: "die Erfahrung", ru: "Опыт" },
  { type: "noun", de: "die Fahrt", ru: "Поездка, езда" },
  { type: "noun", de: "die Gruppe", ru: "Группа" },
  { type: "noun", de: "die Karte", ru: "Карта, билет" },
  { type: "noun", de: "der Service", ru: "Сервис, обслуживание" },
  { type: "noun", de: "der Trend", ru: "Тренд, тенденция" },
  { type: "noun", de: "der Unterricht", ru: "Занятие, урок, обучение" },
  { type: "noun", de: "die Mode", ru: "Мода" },
  { type: "noun", de: "die Erholung", ru: "Отдых, восстановление сил" },
  { type: "noun", de: "die Entspannung", ru: "Расслабление, отдых" },
  { type: "noun", de: "die Anstrengung", ru: "Усилие, напряжение" },
  { type: "noun", de: "die Ausrüstung", ru: "Снаряжение, экипировка" },
  { type: "noun", de: "die Übernachtung", ru: "Ночевка, ночлег" },
  { type: "noun", de: "das Wandern", ru: "Пеший туризм, походы" },
  { type: "noun", de: "die Anmeldung", ru: "Регистрация, заявка" },
  { type: "noun", de: "der Wald", ru: "Лес" },
  { type: "noun", de: "der Frosch", ru: "Лягушка" },
  { type: "noun", de: "das Meer", ru: "Море" },
  { type: "noun", de: "der See", ru: "Озеро" },
  { type: "noun", de: "der Fluss", ru: "Река" },
  { type: "noun", de: "der Berg", ru: "Гора" },
  { type: "noun", de: "der Hügel", ru: "Холм" },

  // ГЛАГОЛЫ
  { type: "verb", de: "wandern", perfekt: "ist gewandert", ru: "Путешествовать", context: { de: "Wir sind am Wochenende im Wald gewandert.", ru: "В выходные мы ходили в поход в лес." } },
  { type: "verb", de: "anbieten", perfekt: "hat angeboten", ru: "Предлагать", context: { de: "Das Hotel hat uns einen guten Service angeboten.", ru: "Отель предложил нам хорошее обслуживание." } },
  { type: "verb", de: "beraten", perfekt: "hat beraten", ru: "Консультировать, советовать", context: { de: "Der Verkäufer hat den Kunden gut beraten.", ru: "Продавец хорошо проконсультировал клиента." } },
  { type: "verb", de: "beginnen", perfekt: "hat begonnen", ru: "Начинать, начинаться", context: { de: "Der Unterricht hat pün切лихь begonnen.", de: "Der Unterricht hat pünktlich begonnen.", ru: "Занятие началось вовремя." } },
  { type: "verb", de: "buchen", perfekt: "hat gebucht", ru: "Бронировать", context: { de: "Ich habe online eine Übernachtung gebucht.", ru: "Я забронировал ночлег онлайн." } },
  { type: "verb", de: "enden", perfekt: "hat geendet", ru: "Кончаться, завершаться", context: { de: "Die Fahrt hat am Bahnhof geendet.", ru: "Поездка завершилась на вокзале." } },
  { type: "verb", de: "erleben", perfekt: "hat erlebt", ru: "Переживать, испытывать (на опыте)", context: { de: "In den Bergen haben wir viel Schönes erlebt.", ru: "В горах мы пережили много прекрасного." } },
  { type: "verb", de: "mit ∙ machen", perfekt: "hat mitgemacht", ru: "Участвовать, делать вместе с кем-то", context: { de: "Alle Personen aus unserer Gruppe haben mitgemacht.", ru: "Все люди из нашей группы приняли участие." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "aktiv", ru: "Активный" },
  { type: "other", de: "sportlich", ru: "Спортивный" },
  { type: "other", de: "überhaupt nicht", ru: "Вообще не, совсем не" },
  { type: "other", de: "anders", ru: "Иначе, по-другому" },
  { type: "other", de: "außerdem", ru: "Кроме того, к тому же" },
  { type: "other", de: "direkt", ru: "Прямо, непосредственно" },
  { type: "other", de: "liegen in", perfekt: "hat gelegen", ru: "Лежать в, находиться в" },
  { type: "other", de: "liegen im Trend", perfekt: "hat im Trend gelegen", ru: "Быть в тренде, быть популярным" }
],
"Урок 4": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "die Banane", ru: "Банан" },
  { type: "noun", de: "die Birne", ru: "Груша" },
  { type: "noun", de: "die Bohne", ru: "Фасоль" },
  { type: "noun", de: "der/das Bonbon", ru: "Конфета, леденец" },
  { type: "noun", de: "die Cola", ru: "Кола" },
  { type: "noun", de: "das Gemüse", ru: "Овощи" },
  { type: "noun", de: "das Getränk", ru: "Напиток" },
  { type: "noun", de: "die Marmelade", ru: "Варенье, джем" },
  { type: "noun", de: "das Mehl", ru: "Мука" },
  { type: "noun", de: "der Quark", ru: "Творог" },
  { type: "noun", de: "der Saft", ru: "Сок" },
  { type: "noun", de: "die Dose", ru: "Консервная банка" },
  { type: "noun", de: "das Gramm", ru: "Грамм" },
  { type: "noun", de: "das Kilogramm", ru: "Килограмм" },
  { type: "noun", de: "der Liter", ru: "Литр" },
  { type: "noun", de: "die Packung", ru: "Упаковка, пачка" },
  { type: "noun", de: "das Pfund", ru: "Фунт, полкилограмма" },
  { type: "noun", de: "die Portion", ru: "Порция" },
  { type: "noun", de: "die Tüte", ru: "Пакет, кулёк" },
  { type: "noun", de: "der Zettel", ru: "Записка, листок бумаги" },
  { type: "noun", de: "der Einkaufszettel", ru: "Список покупок" },
  { type: "noun", de: "die Gewohnheit", ru: "Привычка" },
  { type: "noun", de: "die Essgewohnheit", ru: "Привычки в еде" },
  { type: "noun", de: "der Fehler", ru: "Ошибка" },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "fett", ru: "жирный" },
  { type: "other", de: "fettarm", ru: "с низким содержанием жира", hint: "обезжиренный" },
  { type: "other", de: "frisch", ru: "свежий" },
  { type: "other", de: "hart", ru: "твёрдый, жёсткий" },
  { type: "other", de: "mager", ru: "постный, нежирный", hint: "о мясе, твороге" },
  { type: "other", de: "normal", ru: "нормальный, обычный" },
  { type: "other", de: "roh", ru: "сырой" },
  { type: "other", de: "weich", ru: "мягкий" },
  { type: "other", de: "hungrig", ru: "голодный" },
  { type: "other", de: "satt", ru: "сытый" },
  { type: "other", de: "je", ru: "по" },
  { type: "other", de: "pro", ru: "в, за, на" },
  { type: "other", de: "nämlich", ru: "а именно, ведь, так как" },

  // ГЛАГОЛЫ
  { type: "verb", de: "bestellen", perfekt: "hat bestellt", ru: "заказывать", context: { de: "Wir haben Pizza bestellt.", ru: "Мы заказали пиццу." } },
  { type: "verb", de: "hoffen", perfekt: "hat gehofft", ru: "надеяться", context: { de: "Ich hoffe, das Essen schmeckt dir.", ru: "Надеюсь, тебе понравится еда." } }
],
"Урок 5": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "der Besuch", ru: "Визит, посетитель" },
  { type: "noun", de: "der Club", ru: "Клуб" },
  { type: "noun", de: "die Ferien", ru: "Каникулы", hint: "только мн. ч." },
  { type: "noun", de: "die Führung", ru: "Экскурсия", hint: "с гидом" },
  { type: "noun", de: "die Kamera", ru: "Камера" },
  { type: "noun", de: "die Mauer", ru: "Стена", hint: "Stadtmauer - городская стена" },
  { type: "noun", de: "der Prospekt", ru: "Проспект, брошюра, буклет" },
  { type: "noun", de: "der Reiseführer", ru: "Гид, путеводитель", hint: "человек или книга" },
  { type: "noun", de: "der Rundgang", ru: "Обход, экскурсия, тур" },
  { type: "noun", de: "die Sehenswürdigkeit", ru: "Достопримечательность" },
  { type: "noun", de: "der Tourist", ru: "Турист" },
  { type: "noun", de: "das Trinkgeld", ru: "Чаевые" },
  { type: "noun", de: "die Unterkunft", ru: "Жильё, проживание" },
  { type: "noun", de: "die Nachricht", ru: "Новость, сообщение" },
  { type: "noun", de: "die Postkarte", ru: "Открытка" },
  { type: "noun", de: "der Supermarkt", ru: "Супермаркет" },
  { type: "noun", de: "der Wunsch", ru: "Желание" },

  // ГЛАГОЛЫ
  { type: "verb", de: "besichtigen", perfekt: "hat besichtigt", ru: "осматривать", context: { de: "Wir haben gestern die Altstadt besichtigt.", ru: "Вчера мы осмотрели старый город." } },
  { type: "verb", de: "interessieren sich", perfekt: "hat sich interessiert", ru: "интересоваться", context: { de: "Er interessiert sich для немецкой культуры.", de: "Er interessiert sich für deutsche Kultur.", ru: "Он интересуется немецкой культурой." } },
  { type: "verb", de: "wechseln", perfekt: "hat gewechselt", ru: "менять, обменивать", context: { de: "Wo kann ich hier Geld wechseln?", ru: "Где я могу обменять здесь деньги?" } },
  { type: "verb", de: "zeigen", perfekt: "hat gezeigt", ru: "показывать", context: { de: "Können Sie mir bitte den Weg zeigen?", ru: "Не могли бы вы показать мне дорогу?" } },
  { type: "verb", de: "ab ∙ geben", perfekt: "hat abgegeben", ru: "сдавать, отдавать", context: { de: "Ich muss meinen Schlüssel an der Rezeption abgeben.", ru: "Мне нужно сдать ключ на стойке регистрации." } },
  { type: "verb", de: "ärgern sich", perfekt: "hat sich geärgert", ru: "злиться, сердиться", context: { de: "Meine Frau hat sich über das schlechte Wetter geärgert.", ru: "Моя жена разозлилась из-за плохой погоды." } },
  { type: "verb", de: "dafür sein", perfekt: "ist dafür gewesen", ru: "быть за", context: { de: "Gehen wir ins Kino? — Ja, ich bin dafür!", ru: "Пойдем в кино? — Я за!" } },
  { type: "verb", de: "dagegen sein", perfekt: "ist dagegen gewesen", ru: "быть против", context: { de: "Er möchte heute nicht lernen, er ist dagegen.", ru: "Он не хочет сегодня учиться, он против." } },
  { type: "verb", de: "freuen sich", perfekt: "hat sich gefreut", ru: "радоваться", context: { de: "Ich habe mich über dein Geschenk sehr gefreut.", ru: "Я очень обрадовался твоему подарку." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "berühmt", ru: "знаменитый, известный" },
  { type: "other", de: "geöffnet / offen", ru: "открытый" },
  { type: "other", de: "bunt", ru: "разноцветный, пестрый, яркий" },
  { type: "other", de: "einverstanden", ru: "согласен, согласна" },
  { type: "other", de: "bestimmt", ru: "определенно, точно" },
  { type: "other", de: "meistens", ru: "в большей мере" },
  { type: "other", de: "später", ru: "позже, потом" }
],
"Урок 6": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "die Bühne", ru: "Сцена" },
  { type: "noun", de: "die Diskussion", ru: "Дискуссия" },
  { type: "noun", de: "der Eintritt", ru: "Вход", hint: "плата за вход" },
  { type: "noun", de: "die Ermäßigung", ru: "Скидка" },
  { type: "noun", de: "das Festival", ru: "Фестиваль" },
  { type: "noun", de: "die Karte", ru: "Билет, карта" },
  { type: "noun", de: "die Eintrittskarte", ru: "Входной билет" },
  { type: "noun", de: "die Kinokarte", ru: "Билет в кино" },
  { type: "noun", de: "das Kostüm", ru: "Карнавальный костюм" },
  { type: "noun", de: "die Kunst", ru: "Искусство" },
  { type: "noun", de: "der Künstler", ru: "Деятель искусств" },
  { type: "noun", de: "die Veranstaltung", ru: "Мероприятие" },
  { type: "noun", de: "der Vortrag", ru: "Доклад" },
  { type: "noun", de: "der Vorschlag", ru: "Предложение" },
  { type: "noun", de: "das Feuer", ru: "Огонь" },
  { type: "noun", de: "das Mal", ru: "Раз, первый раз" },

  // ГЛАГОЛЫ
  { type: "verb", de: "erleben", perfekt: "hat erlebt", ru: "переживать, испытывать", context: { de: "Wir have в отпуске много прекрасного erlebt.", de: "Wir haben im Urlaub viel Schönes erlebt.", ru: "В отпуске мы пережили много прекрасного." } },
  { type: "verb", de: "statt ∙ finden", perfekt: "hat stattgefunden", ru: "состояться, проходить", context: { de: "Das Konzert findet morgen statt.", ru: "Концерт состоится завтра." } },
  { type: "verb", de: "zahlen", perfekt: "hat gezahlt", ru: "платить", context: { de: "Ich möchte bitte zahlen.", ru: "Я хотел бы заплатить, пожалуйста." } },
  { type: "verb", de: "aus ∙ machen", perfekt: "hat ausgemacht", ru: "договариваться о чем-то, согласовывать детали", context: { de: "Wir haben einen festen Preis ausgemacht.", ru: "Мы договорились о твердой цене." } },
  { type: "verb", de: "verabreden sich", perfekt: "hat sich verabredet", ru: "договариваться с кем-то", context: { de: "Ich habe mich mit meiner Frau verabredet.", ru: "Я договорился о встрече со своей женой." } },
  { type: "verb", de: "halten von", perfekt: "hat gehalten", ru: "быть какого-либо мнения", context: { de: "Was hältst du von diesem Vorschlag?", ru: "Что ты думаешь об этом предложении?" } },
  { type: "verb", de: "hin ∙ fahren", perfekt: "ist hingefahren", ru: "ехать туда", context: { de: "Das Festival ist toll, wir sollten hinfahren.", ru: "Фестиваль отличный, нам стоит туда поехать." } },
  { type: "verb", de: "lassen", perfekt: "hat gelassen", ru: "оставлять, позволять, побуждать к действию", context: { de: "Lass das book на столе.", de: "Lass das Buch auf dem Tisch.", ru: "Оставь книгу на столе." } },
  { type: "verb", de: "mit ∙ kommen", perfekt: "ist mitgekommen", ru: "идти вместе", context: { de: "Kommst du mit ins Kino?", ru: "Ты пойдешь со мной вместе в кино?" } },
  { type: "verb", de: "vor ∙ schlagen", perfekt: "hat vorgeschlagen", ru: "предлагать", context: { de: "Er hat ein gutes Restaurant vorgeschlagen.", ru: "Он предложил хороший ресторан." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "prima", ru: "прекрасно, отлично" },
  { type: "other", de: "über", ru: "более, больше" },
  { type: "other", de: "vom...bis zum", ru: "с...по" },
  { type: "other", de: "von...an", ru: "начиная с..." },
  { type: "other", de: "da", ru: "тут, вот, там" },
  { type: "other", de: "dort", ru: "там" },
  { type: "other", de: "genau", ru: "точно" },
  { type: "other", de: "mal", ru: "-ка (скажи-ка)" },
  { type: "other", de: "ziemlich", ru: "достаточно, довольно, весьма" },
  { type: "other", de: "zusammen", ru: "вместе" },
  { type: "other", de: "spannend", ru: "захватывающе" },
  { type: "other", de: "lass uns...", ru: "давай мы" }
],
"Урок 7": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "die Art", ru: "Вид" },
  { type: "noun", de: "die Sportart", ru: "Вид спорта" },
  { type: "noun", de: "die Diät", ru: "Диета" },
  { type: "noun", de: "die Gesundheit", ru: "Здоровье" },
  { type: "noun", de: "das Gewicht", ru: "Вес" },
  { type: "noun", de: "das Training", ru: "Тренировка" },
  { type: "noun", de: "das Golf", ru: "Гольф" },
  { type: "noun", de: "die Nudel", ru: "Лапша, вермишель" },
  { type: "noun", de: "die Post", ru: "Почта" },
  { type: "noun", de: "der Verein", ru: "Club, союз" },
  { type: "noun", de: "die Stelle", ru: "Место" },

  // ГЛАГОЛЫ
  { type: "verb", de: "ab ∙ nehmen", perfekt: "hat abgenommen", ru: "худеть", context: { de: "Ich möchte ein bisschen abnehmen, deshalb esse ich weniger Zucker.", ru: "Я хочу немного похудеть, поэтому ем меньше сахара." } },
  { type: "verb", de: "aus ∙ ruhen (sich)", perfekt: "hat sich ausgeruht", ru: "отдыхать, отлёживаться", context: { de: "Nach der Arbeit muss ich mich eine Stunde ausruhen.", ru: "После работы мне нужно час отдохнуть." } },
  { type: "verb", de: "trainieren", perfekt: "hat trainiert", ru: "тренироваться", context: { de: "Wie oft trainierst du im Fitnessstudio?", ru: "Как часто ты тренируешься в тренажерном зале?" } },
  { type: "verb", de: "wiegen", perfekt: "hat gewogen", ru: "весить", context: { de: "Das Gepäck wiegt zwanzig Kilo.", ru: "Багаж весит двадцать килограммов." } },
  { type: "verb", de: "empfehlen", perfekt: "hat empfohlen", ru: "рекомендовать", context: { de: "Welchen Film empfiehlst du mir?", ru: "Какой фильм ты мне порекомендуешь?" } },
  { type: "verb", de: "leihen", perfekt: "hat geliehen", ru: "брать напрокат, одалживать", context: { de: "Kann ich mir dein Fahrrad leihen?", ru: "Могу я одолжить у тебя велосипед?" } },
  { type: "verb", de: "öffnen", perfekt: "hat geöffnet", ru: "открывать", context: { de: "Bitte öffne das Fenster, hier ist es heiß.", ru: "Пожалуйста, открой окно, здесь жарко." } },
  { type: "verb", de: "teil ∙ nehmen", perfekt: "hat teilgenommen", ru: "принимать участие в чём-то", context: { de: "Möchtest du an der Sportart teilnehmen?", ru: "Ты хочешь принять участие в этом виде спорта?" } },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "fit", ru: "подтянутый, в форме" },
  { type: "other", de: "frisch", ru: "свежий" },
  { type: "other", de: "frische Luft", ru: "свежий воздух" },
  { type: "other", de: "regelmäßig", ru: "регулярно" },
  { type: "other", de: "selten", ru: "редко" },
  { type: "other", de: "mindestens", ru: "как минимум, по меньшей мере" },
  { type: "other", de: "circa", ru: "приблизительно, около" },
  { type: "other", de: "früh", ru: "рано" },
  { type: "other", de: "morgens", ru: "по утрам / утром" },
  { type: "other", de: "vormittags", ru: "до обеда (в первой половине дня)" },
  { type: "other", de: "mittags", ru: "в обед / полдень" },
  { type: "other", de: "nachmittags", ru: "после обеда (во второй половине дня)" },
  { type: "other", de: "abends", ru: "по вечерам / вечером" },
  { type: "other", de: "nachts", ru: "ночью / по ночам" },
  { type: "other", de: "montags", ru: "по понедельникам" },
  { type: "other", de: "dienstags", ru: "по вторникам" },
  { type: "other", de: "mittwochs", ru: "по средам" },
  { type: "other", de: "donnerstags", ru: "по четвергам" },
  { type: "other", de: "freitags", ru: "по пятницам" },
  { type: "other", de: "samstags", ru: "по субботам" },
  { type: "other", de: "sonntags", ru: "по воскресеньям" },
  { type: "other", de: "andere", ru: "другие" },
  { type: "other", de: "zwischen", ru: "между" },
  { type: "other", de: "zwischen sieben und viertel nach sieben", ru: "между семью и четвертью восьмого (между 7:00 и 7:15)" },
  { type: "other", de: "an Ihrer Stelle", ru: "на вашем месте" }
],
"Урок 8": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "der Krankenwagen", ru: "Машина скорой помощи" },
  { type: "noun", de: "der Notarzt", ru: "Врач скорой помощи" },
  { type: "noun", de: "die Notaufnahme", ru: "Отделение неотложной помощи" },
  { type: "noun", de: "der Notfall", ru: "Экстренный случай, чрезвычайная ситуация" },
  { type: "noun", de: "der Unfall", ru: "Несчастный случай, авария" },
  { type: "noun", de: "die Verletzung", ru: "Травма, ранение" },
  { type: "noun", de: "das Blut", ru: "Кровь" },
  { type: "noun", de: "die Grippe", ru: "Грипп" },
  { type: "noun", de: "das Herz", ru: "Сердце" },
  { type: "noun", de: "die Krankheit", ru: "Болезнь" },
  { type: "noun", de: "der Magen", ru: "Желудок" },
  { type: "noun", de: "die Operation", ru: "Операция" },
  { type: "noun", de: "die Sprechstunde", ru: "Приемные часы" },
  { type: "noun", de: "die Untersuchung", ru: "Обследование, осмотр" },
  { type: "noun", de: "der Verband", ru: "Повязка, бинт" },
  { type: "noun", de: "der Satz", ru: "Предложение" },
  { type: "noun", de: "die Sorge", ru: "Забота, беспокойство" },
  { type: "noun", de: "die Wahrheit", ru: "Правда" },

  // ГЛАГОЛЫ
  { type: "verb", de: "verletzen sich", perfekt: "hat sich verletzt", ru: "Пораниться, получить травму", context: { de: "Er hat sich beim Kochen am Finger verletzt.", ru: "Он поранил палец во время готовки." } },
  { type: "verb", de: "bluten", perfekt: "hat geblutet", ru: "Кровоточить", context: { de: "Die Wunde hat stark geblutet.", ru: "Рана сильно кровоточила." } },
  { type: "verb", de: "operieren", perfekt: "hat operiert", ru: "Оперировать", context: { de: "Der Arzt hat den Patienten gestern operiert.", ru: "Вчера врач прооперировал пациента." } },
  { type: "verb", de: "sterben", perfekt: "ist gestorben", ru: "Умирать", context: { de: "Der berühmte Künstler ist im Alter von 80 Jahren gestorben.", ru: "Знаменитый художник умер в возрасте 80 лет." } },
  { type: "verb", de: "untersuchen", perfekt: "hat untersucht", ru: "Обследовать, осматривать", context: { de: "Der Arzt hat das Kind gründlich untersucht.", ru: "Врач тщательно обследовал ребёнка." } },
  { type: "verb", de: "verbinden", perfekt: "hat Jobундин", de: "verbinden", perfekt: "hat verbunden", ru: "Перевязывать", context: { de: "Die Krankenschwester hat mein Bein verbunden.", ru: "Медсестра перевязала мне ногу." } },
  { type: "verb", de: "hin ∙ fallen", perfekt: "ist hingefallen", ru: "Падать, упасть", context: { de: "Das Kind ist auf dem Spielplatz hingefallen.", ru: "Ребёнок упал на игровой площадке." } },
  { type: "verb", de: "vertrauen", perfekt: "hat vertraut", ru: "Доверять", context: { de: "Ich habe meinem Arzt immer vertraut.", ru: "Я всегда доверял своему врачу." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "erkältet sein", ru: "Быть простуженным" },
  { type: "other", de: "sich Sorgen machen", ru: "Беспокоиться" },
  { type: "other", de: "los sein", ru: "Происходить" },
  { type: "other", de: "weil", ru: "Потому что" },
  { type: "other", de: "deshalb", ru: "Поэтому" }
],
"Урок 9": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "der Angestellte", ru: "служащий" },
  { type: "noun", de: "die Angestellte", ru: "служащая" },
  { type: "noun", de: "der Arbeiter", ru: "работник" },
  { type: "noun", de: "die Bedingung", ru: "условие" },
  { type: "noun", de: "der Betrieb", ru: "предприятие" },
  { type: "noun", de: "der Erfolg", ru: "успех" },
  { type: "noun", de: "der Export", ru: "экспорт" },
  { type: "noun", de: "die Halle", ru: "цех / зал" },
  { type: "noun", de: "der Import", ru: "импорт" },
  { type: "noun", de: "das Lager", ru: "склад" },
  { type: "noun", de: "der Lkw (Lastkraftwagen)", ru: "грузовик" },
  { type: "noun", de: "der Lohn", ru: "зарплата" },
  { type: "noun", de: "die Maschine", ru: "машина / станок" },
  { type: "noun", de: "der Mitarbeiter", ru: "сотрудник" },
  { type: "noun", de: "die Produktion", ru: "производство / продукция" },
  { type: "noun", de: "das Prozent", ru: "процент" },
  { type: "noun", de: "das Team", ru: "команда" },
  { type: "noun", de: "das Werk", ru: "завод" },
  { type: "noun", de: "die Wirtschaft", ru: "экономика / хозяйство" },
  { type: "noun", de: "der Bericht", ru: "отчет / сообщение" },
  { type: "noun", de: "das Jahrzehnt", ru: "десятилетие" },
  { type: "noun", de: "der Kontakt", ru: "контакт" },
  { type: "noun", de: "die Reparatur", ru: "ремонт" },
  { type: "noun", de: "der Wagen", ru: "автомобиль / машина" },

  // ГЛАГОЛЫ
  { type: "verb", de: "sinken", perfekt: "ist gesunken", ru: "падать / понижаться", context: { de: "Die Preise sind gesunken.", ru: "Цены упали." } },
  { type: "verb", de: "sparen", perfekt: "hat gespart", ru: "экономить / копить", context: { de: "Wir müssen Strom sparen.", ru: "Мы должны экономить электроэнергию." } },
  { type: "verb", de: "steigen", perfekt: "ist gestiegen", ru: "подниматься / расти", context: { de: "Die Produktion ist gestiegen.", ru: "Производство выросло." } },
  { type: "verb", de: "erklären", perfekt: "hat erklärt", ru: "объяснять / разъяснять", context: { de: "Er erklärt mir die Aufgabe.", ru: "Он объясняет мне задачу." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ
  { type: "other", de: "selbstständig", ru: "самостоятельный" },
  { type: "other", de: "international", ru: "международный" },
  { type: "other", de: "dringend", ru: "срочно / срочный" }
],
"Урок 10": [
  // СУЩЕСТВИТЕЛЬНЫЕ 
  { type: "noun", de: "das Besteck", ru: "столовые приборы" },
  { type: "noun", de: "die Gabel", ru: "вилка" },
  { type: "noun", de: "das Glas", ru: "стакан / бокал" },
  { type: "noun", de: "die Kanne", ru: "кувшин / кофейник / чайник" },
  { type: "noun", de: "der Löffel", ru: "ложка" },
  { type: "noun", de: "das Lokal", ru: "заведение общественного питания" },
  { type: "noun", de: "das Messer", ru: "нож" },
  { type: "noun", de: "die Rechnung", ru: "счёт" },
  { type: "noun", de: "die Tasse", ru: "чашка" },
  { type: "noun", de: "der Teller", ru: "тарелка" },
  { type: "noun", de: "der Essig", ru: "уксус" },
  { type: "noun", de: "das Hähnchen", ru: "курочка / цыпленок" },
  { type: "noun", de: "das Öl", ru: "растительное масло / нефть" },
  { type: "noun", de: "die Pommes frites", ru: "картофель фри" },
  { type: "noun", de: "das Salz", ru: "соль" },
  { type: "noun", de: "die Soße", ru: "соус" },
  { type: "noun", de: "das Schnitzel", ru: "шницель" },
  { type: "noun", de: "das Steak", ru: "стейк" },
  { type: "noun", de: "der Zucker", ru: "сахар" },
  { type: "noun", de: "der Augenblick", ru: "мгновение, миг" },
  { type: "noun", de: "der Moment", ru: "момент" },

  // ГЛАГОЛЫ 
  { type: "verb", de: "reservieren", perfekt: "hat reserviert", ru: "бронировать, резервировать", context: { de: "Er hat einen Tisch im Restaurant reserviert.", ru: "Он забронировал столик в ресторане." } },
  { type: "verb", de: "stimmen", perfekt: "hat gestimmt", ru: "соответствовать, быть верным", context: { de: "Das stimmt!", ru: "Это верно!" } },
  { type: "verb", de: "reagieren", perfekt: "hat reagiert", ru: "реагировать", context: { de: "Er hat schnell auf die Frage reagiert.", ru: "Он быстро отреагировал на вопрос." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ И ФРАЗЫ 
  { type: "other", de: "sondern", ru: "а (не..., а...)" },
  { type: "other", de: "dass", ru: "что (союз)" },
  { type: "other", de: "wenigstens", ru: "по крайней мере / как минимум / хотя бы" },
  { type: "other", de: "Die Rechnung, bitte!", ru: "Счёт, пожалуйста!" },
  { type: "other", de: "Stimmt so.", ru: "Сдачи не надо." },
  { type: "other", de: "zusammen zahlen", ru: "платить вместе" },
  { type: "other", de: "getrennt zahlen", ru: "платить раздельно" },
  { type: "other", de: "einen Augenblick bitte", ru: "минуточку, пожалуйста" },
  { type: "other", de: "einen Moment bitte", ru: "секундочку, пожалуйста" },
  { type: "other", de: "Verzeihen Sie", ru: "простите / извините" }
],
"Урок 11": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "der Kunde", ru: "клиент / покупатель" },
  { type: "noun", de: "die Notiz", ru: "заметка" },
  { type: "noun", de: "der Notizblock", ru: "блокнот" },
  { type: "noun", de: "die Werkstatt", ru: "мастерская" },
  { type: "noun", de: "der Briefumschlag", ru: "конверт" },
  { type: "noun", de: "die Handtasche", ru: "женская сумка" },
  { type: "noun", de: "der Artikel", ru: "статья / артикль" },
  { type: "noun", de: "der Erwachsene", ru: "взрослый" },
  { type: "noun", de: "die Erwachsene", ru: "взрослая" },
  { type: "noun", de: "der Grund", ru: "причина" },
  { type: "noun", de: "die Meinung", ru: "мнение" },
  { type: "noun", de: "der Schmuck", ru: "украшение" },
  { type: "noun", de: "der Stoff", ru: "ткань / материал" },

  // ГЛАГОЛЫ
  { type: "verb", de: "her ∙ stellen", perfekt: "hat hergestellt", ru: "производить", context: { de: "Die Firma stellt Möbel her.", ru: "Фирма производит мебель." } },
  { type: "verb", de: "organisieren", perfekt: "hat organisiert", ru: "организовывать", context: { de: "Er hat das Treffen gut organisiert.", ru: "Он хорошо организовал встречу." } },
  { type: "verb", de: "verwenden", perfekt: "hat verwendet", ru: "использовать", context: { de: "Welches Werkzeug verwendest du?", ru: "Какое инструмент ты используешь?" } },
  { type: "verb", de: "weg ∙ werfen", perfekt: "hat weggeworfen", ru: "выбрасывать", context: { de: "Du musst das nicht wegwerfen.", ru: "Тебе не нужно это выбрасывать." } },
  { type: "verb", de: "sich bedanken", perfekt: "hat sich bedankt", ru: "благодарить", context: { de: "Er hat sich für das Geschenk bedankt.", ru: "Он поблагодарил за подарок." } },
  { type: "verb", de: "wünschen", perfekt: "hat gewünscht", ru: "желать", context: { de: "Ich wünsche dir viel Erfolg.", ru: "Я желаю тебе больших успехов." } },
  { type: "verb", de: "sich erinnern", perfekt: "hat sich erinnert", ru: "вспоминать", context: { de: "Ich erinnere mich gut daran.", ru: "Я хорошо это помню (вспоминаю)." } },
  { type: "verb", de: "sich fühlen", perfekt: "hat sich gefühlt", ru: "чувствовать себя", context: { de: "Wie fühlst du dich heute?", ru: "Как ты себя чувствуешь сегодня?" } },
  { type: "verb", de: "streiten", perfekt: "hat gestritten", ru: "спорить / ссориться", context: { de: "Sie haben lange gestritten.", ru: "Они долго спорили." } },
  { type: "verb", de: "unterhalten", perfekt: "hat unterhalten", ru: "беседовать / развлекаться", context: { de: "Wir haben uns gut unterhalten.", ru: "Мы хорошо побеседовали." } },
  { type: "verb", de: "verlieren", perfekt: "hat verloren", ru: "терять / проигрывать", context: { de: "Er hat seinen Schlüssel verloren.", ru: "Он потерял свой ключ." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ (Прилагательные, выражения, фразы)
  { type: "other", de: "froh", ru: "радостный" },
  { type: "other", de: "jung", ru: "молодой" },
  { type: "other", de: "schrecklich", ru: "ужасный" },
  { type: "other", de: "stark", ru: "сильный" },
  { type: "other", de: "viel Erfolg", ru: "удачи / успехов" },
  { type: "other", de: "viel Glück", ru: "много счастья / удачи" },
  { type: "other", de: "meiner Meinung nach", ru: "по моему мнению" },
  { type: "other", de: "willkommen", ru: "добро пожаловать" }
],
"Урок 12": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "der Alkohol", ru: "алкоголь" },
  { type: "noun", de: "das Gericht", ru: "блюдо" },
  { type: "noun", de: "das Getreide", ru: "злаки, пшеница" },
  { type: "noun", de: "das Huhn", ru: "курица" },
  { type: "noun", de: "das Hühnerfleisch", ru: "куриное мясо" },
  { type: "noun", de: "das Lebensmittel", ru: "продукты питания" },
  { type: "noun", de: "die Limonade", ru: "лимонад" },
  { type: "noun", de: "das Mineralwasser", ru: "минеральная вода" },
  { type: "noun", de: "das Rind", ru: "крупный рогатый скот, бык или корова" },
  { type: "noun", de: "das Rindfleisch", ru: "говядина" },
  { type: "noun", de: "das Schwein", ru: "свинья" },
  { type: "noun", de: "das Schweinefleisch", ru: "свинина" },
  { type: "noun", de: "die Hälfte", ru: "половина" },
  { type: "noun", de: "der Deutsche", ru: "немец" },
  { type: "noun", de: "die Deutsche", ru: "немка" },
  { type: "noun", de: "die Heimat", ru: "родина" },
  { type: "noun", de: "die Zeitschrift", ru: "журнал" },

  // ГЛАГОЛЫ
  { type: "verb", de: "braten", perfekt: "hat gebraten", ru: "жарить", context: { de: "Er hat das Fleisch gebraten.", ru: "Он пожарил мясо." } },
  { type: "verb", de: "an ∙ sehen", perfekt: "hat angesehen", ru: "смотреть, рассматривать", context: { de: "Er hat das Foto angesehen.", ru: "Он посмотрел на фотографию." } },
  { type: "verb", de: "aus ∙ suchen", perfekt: "hat ausgesucht", ru: "выбирать, подыскивать", context: { de: "Sie hat ein Geschenk ausgesucht.", ru: "Она выбрала подарок." } },
  { type: "verb", de: "holen", perfekt: "hat geholt", ru: "брать, приносить, забирать", context: { de: "Er hat Wasser geholt.", ru: "Он принес воды." } },
  { type: "verb", de: "überraschen", perfekt: "hat überrascht", ru: "удивлять, поражать", context: { de: "Das hat mich überrascht.", ru: "Это меня удивило." } },
  { type: "verb", de: "verbrauchen", perfekt: "hat verbraucht", ru: "потреблять, расходовать", context: { de: "Мы израсходовали много энергии.", ru: "Wir haben viel Energie verbraucht." } },
  { type: "verb", de: "sich vor ∙ bereiten", perfekt: "hat sich vorbereitet", ru: "готовиться", context: { de: "Er hat sich auf die Prüfung vorbereitet.", ru: "Он подготовился к экзамену." } },
  { type: "verb", de: "sich wundern", perfekt: "hat sich gewundert", ru: "удивляться, изумляться", context: { de: "Ich habe mich gewundert.", ru: "Я удивился." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ (Прилагательные, фразы, наречия)
  { type: "other", de: "scharf", ru: "острый" },
  { type: "other", de: "vegetarisch", ru: "вегетарианский" },
  { type: "other", de: "doppelt", ru: "вдвое, двойной" },
  { type: "other", de: "doppelt so viele", ru: "вдвое больше" },
  { type: "other", de: "durchschnittlich", ru: "в среднем, средний" },
  { type: "other", de: "genug", ru: "достаточно" },
  { type: "other", de: "häufig", ru: "часто, частый" },
  { type: "other", de: "kaum", ru: "едва, вряд ли" },
  { type: "other", de: "rund", ru: "около, примерно (также: круглый)" },
  { type: "other", de: "ein Deutscher", ru: "один немец" },
  { type: "other", de: "eine Deutsche", ru: "одна немка" },
  { type: "other", de: "preiswert", ru: "доступный по цене, недорогой" },
  { type: "other", de: "wahrscheinlich", ru: "вероятно, возможно" },
  { type: "other", de: "komisch", ru: "странный, смешной" },
  { type: "other", de: "wenn – dann", ru: "если ..., то ..." }
],
"Урок 13": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "die Aufgabe", ru: "задание, задача" },
  { type: "noun", de: "das Goethe-Institut", ru: "Институт им. Гёте" },
  { type: "noun", de: "die Klasse", ru: "класс" },
  { type: "noun", de: "die Nachrichten", ru: "новости" },
  { type: "noun", de: "das Semester", ru: "семестр" },
  { type: "noun", de: "die Sprachenschule", ru: "языковая школа" },
  { type: "noun", de: "der Test", ru: "тест" },
  { type: "noun", de: "der Typ", ru: "тип" },
  { type: "noun", de: "der Lernertyp", ru: "тип учащегося" },
  { type: "noun", de: "die Volkshochschule", ru: "вечерняя народная школа" },
  { type: "noun", de: "die Gegenwart", ru: "настоящее время" },
  { type: "noun", de: "die Vergangenheit", ru: "прошлое, прошедшее время" },

  // ГЛАГОЛЫ
  { type: "verb", de: "an ∙ schauen", perfekt: "hat angeschaut", ru: "смотреть, рассматривать", context: { de: "Er hat das Bild angeschaut.", ru: "Он посмотрел на картину." } },
  { type: "verb", de: "auf ∙ schreiben", perfekt: "hat aufgeschrieben", ru: "записывать", context: { de: "Ich habe die Adresse aufgeschrieben.", ru: "Я записал адрес." } },
  { type: "verb", de: "sich bewegen", perfekt: "hat sich bewegt", ru: "двигаться, шевелиться", context: { de: "Er hat sich kaum bewegt.", ru: "Он едва двигался." } },
  { type: "verb", de: "korrigieren", perfekt: "hat korrigiert", ru: "проверять, исправлять", context: { de: "Der Lehrer hat den Test korrigiert.", ru: "Учитель проверил тест." } },
  { type: "verb", de: "lösen", perfekt: "hat gelöst", ru: "решать, отгадывать", context: { de: "Wir haben die Aufgabe gelöst.", ru: "Мы решили задачу." } },
  { type: "verb", de: "sich merken", perfekt: "hat sich gemerkt", ru: "запоминать, замечать", context: { de: "Ich habe mir das Wort gemerkt.", ru: "Я запомнил это слово." } },
  { type: "verb", de: "übersetzen", perfekt: "hat übersetzt", ru: "переводить", context: { de: "Er hat den Text übersetzt.", ru: "Он перевел текст." } },
  { type: "verb", de: "wiederholen", perfekt: "hat wiederholt", ru: "повторять", context: { de: "Wir haben die Wörter wiederholt.", ru: "Мы повторили слова." } },
  { type: "verb", de: "planen", perfekt: "hat geplant", ru: "планировать", context: { de: "Sie hat die Reise geplant.", ru: "Она спланировала поездку." } },
  { type: "verb", de: "sich verlieben", perfekt: "hat sich verliebt", ru: "влюбляться", context: { de: "Er hat sich in sie verliebt.", ru: "Он влюбился в неё." } },
  { type: "verb", de: "verreisen", perfekt: "ist verreist", ru: "уезжать в поездку/путешествие", context: { de: "Er ist übers Wochenende verreist.", ru: "Он уехал на выходные." } },

  // ДРУГИЕ ЧАСТИ РЕЧИ (Прилагательные, фразы, наречия)
  { type: "other", de: "möglich", ru: "возможный, возможно" },
  { type: "other", de: "so viel wie möglich", ru: "как можно больше" },
  { type: "other", de: "aller", ru: "самый-самый (усилительная приставка)" },
  { type: "other", de: "am allerwichtigsten", ru: "важнее всего, самое важное" },
  { type: "other", de: "als", ru: "как, чем (в сравнениях), когда (в прошлом)" }
],
  "Урок 14": [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { type: "noun", de: "der Absender", ru: "отправитель" },
  { type: "noun", de: "der Briefkasten", ru: "почтовый ящик" },
  { type: "noun", de: "der Empfänger", ru: "получатель" },
  { type: "noun", de: "das Päckchen", ru: "посылочка / бандероль" },
  { type: "noun", de: "das Paket", ru: "посылка" },
  { type: "noun", de: "der Schalter", ru: "касса / окошко" },
  { type: "noun", de: "die Unterschrift", ru: "подпись" },
  { type: "noun", de: "die Creme", ru: "крем" },
  { type: "noun", de: "die Gebrauchsanweisung", ru: "инструкция по эксплуатации" },
  { type: "noun", de: "das Gesicht", ru: "лицо" },
  { type: "noun", de: "der Junge", ru: "мальчик / молодой человек" },
  { type: "noun", de: "das Mädchen", ru: "девочка" },
  { type: "noun", de: "das Projekt", ru: "проект" },
  { type: "noun", de: "der Schritt", ru: "шаг" },
  { type: "noun", de: "die Tafel", ru: "доска" },
  { type: "noun", de: "der Zentimeter", ru: "сантиметр" },

  // ГЛАГОЛЫ
  { type: "verb", de: "ein ∙ packen", perfekt: "hat eingepackt", ru: "упаковывать / запаковывать", context: { de: "Er hat das Geschenk eingepackt.", ru: "Он запаковал подарок." } },
  { type: "verb", de: "packen", perfekt: "hat gepackt", ru: "паковать / собирать (вещи)", context: { de: "Sie hat den Koffer gepackt.", ru: "Она собрала чемодан." } },
  { type: "verb", de: "transportieren", perfekt: "hat transportiert", ru: "перевозить / транспортировать", context: { de: "Das Paket wird transportiert.", ru: "Посылку перевозят." } },
  { type: "verb", de: "unterschreiben", perfekt: "hat unterschrieben", ru: "подписывать", context: { de: "Bitte unterschreiben Sie hier.", ru: "Пожалуйста, подпишите здесь." } },
  { type: "verb", de: "an ∙ kreuzen", perfekt: "hat angekreuzt", ru: "отмечать крестиком", context: { de: "Kreuzen Sie die Antwort an.", ru: "Отметьте ответ крестиком." } },
  { type: "verb", de: "benutzen", perfekt: "hat benutzt", ru: "пользоваться / использовать", context: { de: "Er benutzt das Wörterbuch.", ru: "Он использует словарь." } },
  { type: "verb", de: "denken an", perfekt: "hat an ... gedacht", ru: "думать о (+ Akk.)", context: { de: "Ich denke an dich.", ru: "Я думаю о тебе." } },
  { type: "verb", de: "ergänzen", perfekt: "hat ergänzt", ru: "дополнять / заполнять", context: { de: "Ergänzen Sie den Text.", ru: "Дополните текст." } },
  { type: "verb", de: "gebrauchen", perfekt: "hat gebraucht", ru: "употреблять / использовать", context: { de: "Wann gebraucht man das Wort?", ru: "Когда употребляют это слово?" } },

  // ДРУГИЕ ЧАСТИ РЕЧИ (Прилагательные, наречия)
  { type: "other", de: "arm", ru: "бедный" },
  { type: "other", de: "verschieden", ru: "разный / различный" },
  { type: "other", de: "schließlich", ru: "в конце концов / наконец-то" }
]
};
